'use strict';
gantt.factory('GanttColumnHeader', [ 'moment', 'GanttColumn', function(moment, Column) {
    // Used to display the Gantt grid and header.
    // The columns are generated by the column generator.

    var ColumnHeader = function(date, unit, left, width) {
        var startDate = moment(date);
        var endDate = moment(startDate).add(1, unit);

        var column = new Column(startDate, endDate, left, width);
        column.unit = unit;

        return column;
    };
    return ColumnHeader;
}]);
